### ISSUE TITLE
Setting jPlaylist.playlist from parent component

### ISSUE THREAD

**Issue by appigram** [jplayer/react-jPlaylist#1]
Hi guys,

Thanks for the amazing library!
I'm new in React/Redux, so I have a question about initializing playlists in runtime. How can I to do this?

JPlayer component:
````
import React from 'react';
import { Gui, SeekBar, BufferBar,
  Poster, Audio, Title, Mute, Play, PlayBar,
  VolumeBar, Duration, CurrentTime, Download, BrowserUnsupported,
} from 'react-jplayer';
import JPlaylist, { connect, Playlist, Shuffle, Next, Previous, Repeat,
  MediaLink, Title as PlaylistTitle } from 'react-jplaylist';

const options = {
  id: 'JPlayer',
  verticalVolume: true,
};

const jPlaylistOptions = {
  hidePlaylist: false,
  playlist: INIT_FROM_PARENT,
};

const JPlayer = () => {
  return (<JPlaylist className='jp-sleek'>
    code here...
  </JPlaylist>);
};

export default connect(JPlayer, options, jPlaylistOptions);
````

JPlaylist component:

````
import React, { Component } from 'react';
import { Provider } from 'react-redux';
import { createStore, combineReducers } from 'redux';
import { initialState as jPlayerInitialState, reducer as jPlayers } from 'react-jplayer';
import { initialState as jPlaylistInitialState, reducer as jPlaylists } from 'react-jplaylist';
import JPlayer from './JPlayer';

const store = createStore(combineReducers({
  jPlayers,
  jPlaylists,
}), {
  jPlayers: jPlayerInitialState(JPlayer),
  jPlaylists: jPlaylistInitialState(JPlayer),
}, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__());

class JPlaylist extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    const playlist = this.props.tracks.map(track => {
      return {
        title: track.title,
        artist: track.performer,
        sources: {
          mp3: track.url,
        },
      }
    });
    return (<div className='audio-list'>
      <Provider store={store}>
        <JPlayer playlist={playlist}/>
      </Provider>
    </div>
    );
  }
}

export default JPlaylist;
````

I need to pass **this.props.tracks** from parent component (any page in website) to **INIT_FROM_PARENT** in JPlayer

Thanks for your help!

**Comment by MartinDawson** [comment]
Hi @appigram, good question.

The [setPlaylist(id, playlist)](https://github.com/jplayer/react-jPlaylist#setplaylistid-playlist) action-creator that is provided to you by react-jPlaylist is what you want.

To set the playlist from anywhere in your application here is an example:

```
import React from 'react';
import { actions } from 'react-jplaylist';
import { connect } from 'react-redux';

class SomeRandomComponent extends React.Component {
	componentDidMount() {
	    const myPlaylist = [...];
		
		// By dispatching the react-jPlaylist action we can change
		// the jPlaylist's playlist
		this.props.dispatch(actions.setPlaylist(idOfMyJPlaylist, myPlaylist));
	}
}

// Connecting this component to the store 
// gives us the dispatch function in SomeRandomComponent
export default connect(someRandomComponent);
```

Basically, wherever you want to dynamically change a react-jPlayer or react-jPlaylist option you just do:

1. connect your component to redux store.
2. pass the react-jplayer or react-jplaylist action to dispatch with the values the action requires.

react-jPlaylist will update the playlist in the reducer internally and then the new playlist can be accessed through `mapStateToProps` provided by redux.

Is this what you wanted?

**Comment by MartinDawson** [comment]
I do not like your naming of components. It's really confusing that you are passing `playlist` from your `JPlaylist` to `JPlayer` components and then using react-jplaylist in your `JPlayer` component, it doesn't make much sense when read logically as a JPlayer component shouldn't know about a playlist. I'd consider renaming them.

**Comment by appigram** [comment]
@MartinDawson thanks for your answer, the problem is resolved!
But I see another issue, an audio file is fully downloaded before playing...
JPlaylist AudioPlayer example working fine with the same audio url, I see correct 206 requests

**Comment by appigram** [comment]
I found a problem with 206 partial requests, Service Worker does not work correctly with 206 requests in my app, fixed

**Comment by MartinDawson** [comment]
@appigram Great. Glad you found a fix. As you found out, react-jPlayer doesn't have anything to do with partial requests. The only option that specifies loading is the [preload](https://github.com/jplayer/react-jPlayer#preload-string) option that is automatically set to only download the 'metadata' of the media file.

Closing this issue.
